### ISSUE TITLE
swagger console infini

### ISSUE THREAD

**Issue by pcouas** [ibm-messaging/mq-container#339] opened 2019-06-13 16:03 UTC
Hi,

When i tried on my docker 9.1.2.0 https://localhost:9443/ibm/api/ibmmq/console/
there is an dynamic infinite loop in url !

https://localhost:9443/ibm/api/ibmmq/console/ibmmq/console/ibmmq/console/ibmmq/console/ibmmq/console/ibmmq/console/ibmmq/console

**Comment by ramesh-chandra** [comment] 2019-09-29 17:56
I am also facing the same problem. Did anybody know how to resolve this issue?

**Comment by arthurbarr** [comment] 2021-09-21 08:41
I just tried this on the latest CD release, MQ 9.2.3, and the issue is no longer present.  MQ 9.1.2 is now out of support, so closing this issue.

**Closed by arthurbarr** 2021-09-21 08:41 UTC
