### ISSUE TITLE
After stop container and restart mqweb component does not work

### ISSUE THREAD

**Issue by lucasmori** [ibm-messaging/mq-container#467] opened 2021-08-23 16:07 UTC
I'm just running the latest container from dockerhub. It starts fine but if I stop and restart the mqweb component does not work any longer.

```
2021-08-23T16:02:45.743Z Error 1 starting web server: 
Server mqweb is already running.
2021-08-23T16:02:45.743Z Error starting web server: exit status 1
```

I need to kill my volume and start from zero again, and if I stop or restart the container the same error occurs.

**Comment by lucasmori** [comment] 2021-08-23 16:09
My docker-compose.yaml

```yaml

version: "3.9"

services:
  ibmmq:
    container_name: ibmmq
    image: ibmcom/mq:latest
    ports:
      - "1414:1414"
      - "9443:9443"
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=MQ1
      - MQ_APP_PASSWORD=somepasswordhere
    volumes:
      - qm1data:/mnt/mqm
volumes:
  qm1data: {}
```

**Comment by arthurbarr** [comment] 2022-04-12 08:52
Duplicate of #448

**Closed by arthurbarr** 2022-04-12 08:52 UTC
